title: ring0.info
url: https://ring0.info

permalink: /posts/:title

kramdown:
  input: GFM

disqus_shortname: ring0

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude: ["CNAME"]

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
